version: '3'

services:
  app:
    build: .
    volumes:
      - ../../html:/var/www/html:delegated
      - ~/.composer:/home/root/.composer:delegated
    ports:
      - "8080:80"
    networks:
      - movn

networks:
  movn:
    external: true
    name: movn